/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "com.dmoser.codyssey"
version = project.findProperty("version") ?: error("Version must be provided via -Pversion")
plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.github.gmazzo.buildconfig") version "5.6.5"

}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.jar {
    manifest {
        attributes(
            "Automatic-Module-Name" to
                    "${project.group}.${project.name}"
                        .replace('-', '.')
        )
    }
}

buildConfig {
    packageName(project.group.toString().lowercase() + "." + project.name.lowercase())
    className("Constants")
    documentation.set("Automatically generated class with runtime constants defined in the gradle.properties file.")
    buildConfigField("String", "COMPOSE_VERSION", "\"${project.version}\"")
}


