/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "com.dmoser.codyssey"
version = project.findProperty("version") ?: error("Version must be provided via -Pversion")
val buildConfigClassName = project.name.replaceFirstChar { it.uppercase() } + "BuildConfig"
val defaultSshPort: String by project
val defaultShellName: String by project
val defaultBannerLocation: String by project


plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    alias(libs.plugins.buildconfig)
    alias(libs.plugins.shadow)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(libs.bundles.junit)
    testImplementation(libs.bundles.mockito)
    implementation(libs.bundles.jackson)

    api(libs.slf4j)
    runtimeOnly(libs.bundles.log4j)
    implementation(libs.bundles.jackson)

    implementation(libs.bundles.cli)
    implementation(libs.bundles.ssh)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withJavadocJar()
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
}

java {

}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.jar {
    manifest {
        attributes(
            "Automatic-Module-Name" to
                    "${project.group}.${project.name}"
                        .replace('-', '.')
        )
    }
}

buildConfig {
    packageName(project.group.toString().lowercase() + "." + project.name.lowercase())
    className(buildConfigClassName)
    documentation.set("Automatically generated class with build constants.")
    buildConfigField("String", "VERSION", "\"${project.version}\"")
    buildConfigField("String", "DEFAULT_SSH_PORT", "\"${defaultSshPort}\"")
    buildConfigField("String", "DEFAULT_SHELL_NAME", "\"${defaultShellName}\"")
    buildConfigField("String", "DEFAULT_BANNER_LOCATION", "\"${defaultBannerLocation}\"")
}

tasks {
    shadowJar {
        archiveBaseName.set("bifroest") // Set to your desired jar name
        archiveClassifier.set("example") // Empty to make it the default artifact
        archiveVersion.set("${project.version}");
        manifest {
            attributes["Main-Class"] = "com.dmoser.codyssey.bifroest.Example" // <- Replace with your main class
        }
    }
}

tasks.register<JavaExec>("runExample") {
    group = "application"
    description = "Runs the Bifroest example application."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.dmoser.codyssey.bifroest.Example")
    // Use standard input for interactive CLI
    standardInput = System.`in`
}

tasks.named("generateBuildConfig").configure {
    // Groups the task under the 'documentation' section
    group = "documentation"
    val groupPath = project.group
        .toString()
        .lowercase()
        .replace(".", "/")

    val projectName = project.name.lowercase()
    val className = buildConfigClassName

    val constantsFile = layout.buildDirectory.file(
        "generated/sources/buildConfig/main/$groupPath/$projectName/$className.java"
    )

    doLast {
        val file = constantsFile.get().asFile
        println(file.path)
        if (file.exists()) {
            // Read the file
            var content = file.readText()

            // Add Javadoc comments to fields
            content = content.replace(
                "public static",
                "/** Automatically generated value. */\n  public static"
            )
            // Write the modified content back to the file
            file.writeText(content)
        }
    }
}


