/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import com.dmoser.codyssey.bifroest.BifroestBuildConfig;
import org.junit.jupiter.api.Test;

class LibraryTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    IO.println(BifroestBuildConfig.VERSION);
  }
}
